name: "Connect to GCP VM via ssh and run commands"

on:
  push:
    branches:
      - "main"

env:
  project_id: "dicoding-backend-expert-422420"
  ZONE: "asia-southeast2-c"

jobs:
  ssh:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Set Gcloud SDK
        uses: "google-github-actions/setup-gcloud@master"
        with:
          project_id: "dicoding-backend-expert-422420"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: SSH to VM
        uses: "google-github-actions/ssh-compute@main"
        with:
          project_id: "dicoding-backend-expert-422420"
          zone: ${{ secrets.GCP_ZONE }}
          instance_name: "api-backend-server"
          run: |
            gcloud compute ssh api-backend-server --zone=asia-southeast2-c --tunnel-through-iap
            ls -a
            git pull origin main
            cd ~/ForumAPIv2
            npm install
            npm run migrate up
            npm run migrate:test up
            pm2 restart forumapi-2
