name: "Continuous Deployment"

on:
  push:
    branches:
      - "main"

env:
  project_id: "dicoding-backend-expert-422420"
  ZONE: "asia-southeast2-c"

jobs:
  ssh:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "dicoding-backend-expert-422420"
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set Gcloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: "dicoding-backend-expert-422420"
          version: ">= 363.0.0"

      - name: SSH to VM
        uses: "google-github-actions/ssh-compute@v0"
        with:
          instance_name: "api-backend-server"
          zone: ${{ secrets.GCP_ZONE }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          command: "echo Hello World"

      - id: "test"
        run: |
          git pull origin main
          npm install
          npm install pm2 -g
          npm run migrate up
          npm run migrate:test up
          pm2 restart forumapi-2
