on:
  push:
    branches:
      - "main"

name: "Connect to GCP VM via ssh and run commands"
env:
  ZONE: "asia-southeast2-c"

jobs:
  ssh:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: SSH to VM
        uses: "google-github-actions/ssh-compute@v1"
        with:
          instance_name: "api-backend-server"
          zone: ${{ secrets.GCP_ZONE }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          command: |
            cd ~/ForumAPIv2
            git pull origin main
            npm install
            npm run migrate up
            npm run migrate:test up
            pm2 restart forumapi-2
