name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH connection
        uses: "actions/checkout@v4"

      - name: SSH ke CE
        uses: "google-github-actions/ssh-compute@v1"
        with:
          instance_name: "api-backend-server"
          zone: ${{ secrets.GCP_ZONE }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          command: |
            cd ~/ForumAPIv2
            git pull origin main
            npm install
            npm run migrate up
            npm run migrate:test up
            pm2 restart forumapi-2
