name: Continuous Integration Postgres
on:
  push:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:18.19.1

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: oiunited
          POSTGRES_DB: forumapi2

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install migrate
      - name: Connect to PostgreSQL
        run: npm run migrate
